<?php

namespace App\Filament\Staff\Resources\IncomeResource\Pages;

use App\Filament\Staff\Resources\IncomeResource;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Contracts\Support\Htmlable;

class EditIncome extends EditRecord
{
    protected static string $resource = IncomeResource::class;

    public function getTitle(): string|Htmlable
    {
        return
            __('custom.Edit Income'); // TODO: Change the autogenerated stub
    }

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make(),
        ];
    }

    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('index');
    }

    protected function getCreatedNotificationTitle(): ?string
    {
        return 'Income updated!';
    }

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['user_id'] = auth()->id();
        $data['received_at'] = now();

        return $data;
    }
}
