<?php

namespace App\Filament\Staff\Resources\IncomeResource\Pages;

use App\Filament\Staff\Resources\IncomeResource;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Contracts\Support\Htmlable;

class ListIncomes extends ListRecords
{
    protected static string $resource = IncomeResource::class;

    public function getTitle(): string|Htmlable
    {
        return __('custom.Income'); // TODO: Change the autogenerated stub
    }

    protected function getHeaderActions(): array
    {
        return [
            Actions\CreateAction::make()
                ->label(__('custom.Add Income')),
        ];
    }
}
