<?php

namespace App\Filament\Staff\Resources\UserDayOffResource\Pages;

use App\Filament\Staff\Resources\UserDayOffResource;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Contracts\Support\Htmlable;

class ListUserDayOffs extends ListRecords
{
    protected static string $resource = UserDayOffResource::class;

    public function getTitle(): string|Htmlable
    {
        return  __('custom.Day off'); // TODO: Change the autogenerated stub
    }

    protected function getHeaderActions(): array
    {
        return [
            Actions\CreateAction::make()->label(__('custom.Add Day off')),
        ];
    }
}
